version: 2

models:
  - name: trades_timeseries
    columns:
      - name: tradeId
        tests:
          - not_null
      - name: symbol
        tests:
          - not_null
    tests:
      - dbt_utils.unique_combination_of_columns:
          name: unique_trade_id_per_symbol
          description: "Unique Trade ID for Symbol"
          combination_of_columns:
            - tradeId
            - symbol
